### ISSUE TITLE
The installed version of package kernel is not compatible, require 4.14.120-1-0f2b58b9… while 4.14.111-1-ee1db38e… is installed.

### ISSUE THREAD

**Issue by KamuiX** [iscilyas/openwrt-r3p#5]
Most of the Software (package) installatinons comes with error

`The installed version of package kernel is not compatible, require 4.14.120-1-0f2b58b9… while 4.14.111-1-ee1db38e… is installed.`

Is there any way to force opkg find package builds based on 4.14.111?

**Comment by Tyr808** [comment]
Hi, sorry to bother but I see that you closed this issue and it's the same issue I'm having now, just on a newer version of the firmware and kernel, how did you resolve this?

**Comment by KamuiX** [comment]
Hi Tyr. 
Actually the opkg is looking for the latest versions for some unknown reason to me. (Maybe the latest binary versions opkg see as available by that time from the official repositories)
To solve the problem do the following: 
1) Try to install the pakage you need and check which dependency is missing
2) Let's assume that you are missing kmod-sched-connmark 
3) Go to the page where you downloaded the firmware in my case https://github.com/iscilyas/openwrt-r3p/releases/tag/v4.14.111
4) Download the kmod needed even in the version is compiled for 4.14.111 kernel (opkg asks for 4.14.120 ingore it) https://github.com/iscilyas/openwrt-r3p/releases/download/v4.14.111/kmod-sched-connmark_4.14.111-1_mipsel_24kc.ipk
5) Upload the ipk file to /tmp of your router. An easy way is by using WinScp
6) Connect through SSH to the router and proceed with the bellow commands 
```
  cd /tmp
  opkg install ./kmod-sched-connmark_4.14.111-1_mipsel_24kc.ipk
  opkg update
```
7) Try again to install the package you will not have problem with this dependency again. You may need although to do this procedure 2-3-4 times because another dependency error may pop up.

**Comment by Tyr808** [comment]
Ah okay I think I understand now, appreciate the speedy reply, will try later tonight!  So far I'm loving this new firmware, I just have a relatively busy network and with a few of us being gamers, bufferbloat is the enemy so QoS/SQM is the one thing I was missing.

Thanks again :)
